pipeline {
    agent any

    stages {
        stage('build') {
            steps {
               dotnetBuild configuration: 'Release', project: 'WeatherForecastApi/WeatherForecastApi.csproj', sdk: '.NET 6'
            }
        }
        stage('test') {
            steps {
                dotnetBuild configuration: 'Release', project: 'WeatherForecastApi/WeatherForecastApi.csproj', sdk: '.NET 6'
            }
        }
        stage('docker image') {
            steps {
                sh 'docker build -t weatherforecast -f WeatherForecastApi/Dockerfile .'
            }
        }
        stage('docker run') {
            steps {
                sh 'docker run -d --rm -p 5000:80 weatherforecast'
            }
        }
    }
}