pipeline {
    agent any

    stages {
        stage('checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/singularitydeveloper/WeatherForecast']])
            }
        }
        stage('build') {
            steps {
               dotnetBuild configuration: 'Release', project: 'WeatherForecastApi/WeatherForecastApi.csproj', sdk: '.NET 6'
            }
        }
        stage('test') {
            steps {
                dotnetBuild configuration: 'Release', project: 'WeatherForecastApi/WeatherForecastApi.csproj', sdk: '.NET 6'
            }
        }
        stage('docker image') {
            steps {
                sh 'docker build -t weatherforecast -f WeatherForecastApi .'
            }
        }
        stage('deploy') {
            steps {
                sh 'docker run -d -rm -p 5000:80 weatherforecast'
            }
        }
    }
}